DELETE FROM AUTHOR;
DELETE FROM BOOK;
DELETE FROM BOOK_TITLE;
DELETE FROM BOOK_CATEGORY;

INSERT INTO BOOK_TITLE (ID, BOOK_TITLE,BOOK_TITLE_LANG) VALUES (1,'Everyday Italian','en') ;
INSERT INTO BOOK_TITLE (ID, BOOK_TITLE,BOOK_TITLE_LANG) VALUES (2,'Harry Potter','en') ;
INSERT INTO BOOK_TITLE (ID, BOOK_TITLE,BOOK_TITLE_LANG) VALUES (3,'Learning XML','en') ;

INSERT INTO BOOK_CATEGORY (ID,BOOK_CATEGORY) VALUES (1,'cooking') ;
INSERT INTO BOOK_CATEGORY (ID,BOOK_CATEGORY) VALUES (2,'children') ;
INSERT INTO BOOK_CATEGORY (ID,BOOK_CATEGORY) VALUES (3,'web') ;

INSERT INTO BOOK (ID,BOOK_CATEGORY_ID,BOOK_TITLE_ID,BOOK_YEAR,BOOK_PRICE) VALUES (1,1,1,2005,30.0) ;
INSERT INTO BOOK (ID,BOOK_CATEGORY_ID,BOOK_TITLE_ID,BOOK_YEAR,BOOK_PRICE) VALUES (2,2,2,2005,29.99) ;
INSERT INTO BOOK (ID,BOOK_CATEGORY_ID,BOOK_TITLE_ID,BOOK_YEAR,BOOK_PRICE) VALUES (3,3,3,2003,39.99) ;

INSERT INTO AUTHOR (ID,AUTHOR_NAME,BOOK_ID) VALUES (1,'Giada De Laurentiis',1) ;
INSERT INTO AUTHOR (ID,AUTHOR_NAME,BOOK_ID) VALUES (2,'Sam T. Bruce',1) ;

INSERT INTO AUTHOR (ID,AUTHOR_NAME,BOOK_ID) VALUES (3,'J K. Rowling',2) ;
INSERT INTO AUTHOR (ID,AUTHOR_NAME,BOOK_ID) VALUES (4,'Erik T. Ray',2) ;

INSERT INTO AUTHOR (ID,AUTHOR_NAME,BOOK_ID) VALUES (5,'Erik T. Ray',3) ;